# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
#	AUTHOR: TOLO VICH LOZANO 
#
#	DESCRIPTION:
#		Very simple program for copy with rsync
#		You need to have rsync installed and Pyside
#
#
# Created: mié 01 feb 2023 17:10:54 CET
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
import os
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 126)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 79, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 79, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_file_source = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_file_source.setGeometry(QtCore.QRect(80, 10, 411, 29))
        self.lineEdit_file_source.setObjectName("lineEdit_file_source")
        self.lineEdit_file_dest = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_file_dest.setGeometry(QtCore.QRect(80, 50, 411, 29))
        self.lineEdit_file_dest.setObjectName("lineEdit_file_dest")
        self.pushButton_file_source = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_file_source.setGeometry(QtCore.QRect(500, 10, 111, 29))
        self.pushButton_file_source.setObjectName("pushButton_file_source")
        self.pushButton_file_dest = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_file_dest.setGeometry(QtCore.QRect(500, 50, 111, 29))
        self.pushButton_file_dest.setObjectName("pushButton_file_dest")
        self.pushButton_sync = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sync.setGeometry(QtCore.QRect(80, 90, 111, 29))
        self.pushButton_sync.setObjectName("pushButton_sync")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(380, 90, 111, 29))
        self.pushButton_close.setObjectName("pushButton_close")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_close.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        def openDirectoryDialog():
        	"""
        	Opens a dialog for choose a directory
        	"""

        	d1 = directory = QtWidgets.QFileDialog.getExistingDirectory()
        	self.lineEdit_file_source.setText(d1)
        def openDirectoryDialog2():
        	"""
        	Opens a dialog for choose a directory
        	"""
        	d2 = directory = QtWidgets.QFileDialog.getExistingDirectory()
        	self.lineEdit_file_dest.setText(d2)

        def copiar():

           a = self.lineEdit_file_source.text()
           b = self.lineEdit_file_dest.text()
           c = "rsync -av --progress "+a+" "+b
           os.system(c)        

        QtCore.QObject.connect(self.pushButton_close, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.pushButton_file_source, QtCore.SIGNAL("clicked()"), lambda:openDirectoryDialog())
        QtCore.QObject.connect(self.pushButton_file_dest, QtCore.SIGNAL("clicked()"), lambda:openDirectoryDialog2())
        QtCore.QObject.connect(self.pushButton_sync, QtCore.SIGNAL("clicked()"), copiar)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)  
        

        

      

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Sync"))
        self.label.setText(_translate("MainWindow", "Origen"))
        self.label_2.setText(_translate("MainWindow", "Destino"))
        self.pushButton_file_source.setText(_translate("MainWindow", "Seleccionar"))
        self.pushButton_file_dest.setText(_translate("MainWindow", "Seleccionar"))
        self.pushButton_sync.setText(_translate("MainWindow", "Ejecutar"))
        self.pushButton_close.setText(_translate("MainWindow", "Salir"))

class ControlMainWindow(QtWidgets.QMainWindow):
   def __init__(self, parent=None):
    super(ControlMainWindow, self).__init__(parent)
    self.ui =  Ui_MainWindow()
    self.ui.setupUi(self)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mySW = ControlMainWindow()
    mySW.show()
sys.exit(app.exec_())        
